In [1]:
import pandas as pd
import numpy as np
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [2]:
!ls *.csv

YKSyi erteleyin_answers.csv
demet evgar_answers.csv
kıdem tazminatıma dokunma_answers.csv
serdar hocanın yanındayız_answers.csv


In [53]:
base_questions = ["'a ne oldu", "'e ne oldu",
                  " ne zaman", " nerede ", " neden", " ne için",
                  " kimdir" , " kim" ]

In [4]:
df = pd.read_csv("demet evgar_answers.csv")

In [59]:
def answers_per_questions(df, base_questions):
    for i in range(len(base_questions)):
        x = df.loc[(df.index%len(base_questions))==i].iloc[:,1]
        conf = x.count()/len(x)
        top_words_with_conf = pd.Series([w for ans in x.dropna() for w in ans.split(" ")]).value_counts(1).head(5)
        print(base_questions[i] + " with confidence: " + str(conf)[:4])
        print(top_words_with_conf)
        print(" ")

In [62]:
a = !ls *.csv # cevapların olduğu csv'ler için

In [66]:
df = pd.read_csv(a[0])
print(a[0])
answers_per_questions(df, base_questions)

YKSyi erteleyin_answers.csv
'a ne oldu with confidence: 0.13
olsun                 0.043478
öğrencinin            0.043478
#yksyi2ayerteleyin    0.043478
sınav                 0.043478
yeter                 0.021739
dtype: float64
 
'e ne oldu with confidence: 0.09
olsun      0.06250
ikamet     0.06250
yakın      0.06250
sınav      0.06250
yerlere    0.03125
dtype: float64
 
 ne zaman with confidence: 0.11
#yksyi2ayerteleyin    0.097561
sınav                 0.048780
yks                   0.048780
abi                   0.024390
ben                   0.024390
dtype: float64
 
 nerede  with confidence: 0.14
#yksyi2ayerteleyin    0.040000
ikamet                0.026667
öğrencinin            0.026667
ve                    0.026667
yakın                 0.026667
dtype: float64
 
 neden with confidence: 0.13
#yksyi2ayerteleyin    0.085714
yks                   0.057143
35.000                0.028571
ertelenir             0.028571
ertelenmesi           0.028571
dtype: float64
 
 ne için with 

In [68]:
df = pd.read_csv(a[1])
print(a[1])
answers_per_questions(df, base_questions)

demet evgar_answers.csv
'a ne oldu with confidence: 0.57
2020      0.078947
arı       0.052632
bişey     0.026316
içine     0.026316
kaçmış    0.026316
dtype: float64
 
'e ne oldu with confidence: 0.42
2020     0.085714
sana     0.057143
bişey    0.028571
artık    0.028571
dalga    0.028571
dtype: float64
 
 ne zaman with confidence: 0.42
arı       0.076923
2020      0.076923
demet     0.038462
birkaç    0.038462
ilk       0.038462
dtype: float64
 
 nerede  with confidence: 0.44
arı           0.053571
dudağını      0.035714
sonra         0.035714
sonrasında    0.017857
dudagını      0.017857
dtype: float64
 
 neden with confidence: 0.5
2020         0.085714
arı          0.057143
hastanede    0.057143
birkaç       0.028571
ne           0.028571
dtype: float64
 
 ne için with confidence: 0.27
bişey      0.0625
bu         0.0625
bunu       0.0625
artık      0.0625
yaşında    0.0625
dtype: float64
 
 kimdir with confidence: 0.27
arı          0.2
ayağından    0.1
açmadı       0.1
2020      

In [69]:
df = pd.read_csv(a[2])
print(a[2])
answers_per_questions(df, base_questions)

kıdem tazminatıma dokunma_answers.csv
'a ne oldu with confidence: 0.28
kıdemtazminatımadokunma     0.163265
kıdem                       0.040816
işçinin                     0.040816
#kıdemtazminatımadokunma    0.040816
bir                         0.020408
dtype: float64
 
'e ne oldu with confidence: 0.25
kıdemtazminatımadokunma    0.192771
işçinin                    0.048193
kıdem                      0.036145
geleceğimizi               0.024096
kızımın                    0.024096
dtype: float64
 
 ne zaman with confidence: 0.22
kıdemtazminatımadokunma     0.214286
işçinin                     0.057143
dokunma                     0.042857
kıdemtazminati              0.028571
#kıdemtazminatımadokunma    0.028571
dtype: float64
 
 nerede  with confidence: 0.23
kıdemtazminatımadokunma    0.148515
dokunma                    0.029703
kıdem                      0.029703
ben                        0.019802
bir                        0.019802
dtype: float64
 
 neden with confidence: 0.26
kıdemt

In [70]:
df = pd.read_csv(a[3])
print(a[3])
answers_per_questions(df, base_questions)

serdar hocanın yanındayız_answers.csv
'a ne oldu with confidence: 0.29
serdarhocayanındayız     0.209302
#serdarhocayanındayız    0.139535
yanında                  0.046512
kim                      0.046512
düşünüyor,               0.023256
dtype: float64
 
'e ne oldu with confidence: 0.16
#serdarhocayanındayız    0.178571
serdarhocayanındayız     0.107143
kim                      0.071429
ezilenin                 0.035714
ekonomiyi                0.035714
dtype: float64
 
 ne zaman with confidence: 0.26
serdarhocayanındayız     0.275862
#serdarhocayanındayız    0.206897
kim                      0.068966
ezilenin                 0.034483
düşünüyor,               0.034483
dtype: float64
 
 nerede  with confidence: 0.19
serdarhocayanındayız    0.103448
yanında                 0.068966
kim                     0.034483
oldu                    0.017241
'ın                     0.017241
dtype: float64
 
 neden with confidence: 0.19
serdarhocayanındayız     0.259259
#serdarhocayanındayız    0.

In [72]:
from simpletransformers.question_answering import QuestionAnsweringModel

I0713 11:37:56.232146 4754986432 file_utils.py:39] PyTorch version 1.2.0 available.
I0713 11:37:58.615687 4754986432 file_utils.py:55] TensorFlow version 2.0.0 available.
I0713 11:37:58.789217 4754986432 _import_c_extension.py:31] Failed to import cuda module: No module named 'caffe2.python.caffe2_pybind11_state_gpu'
I0713 11:37:58.790062 4754986432 _import_c_extension.py:38] Failed to import AMD hip module: No module named 'caffe2.python.caffe2_pybind11_state_hip'
W0713 11:37:58.790925 4754986432 _import_c_extension.py:41] This caffe2 python run does not have GPU support. Will run in CPU only mode.


In [89]:
a = QuestionAnsweringModel("bert", "dbmdz/bert-base-turkish-cased", torch.Generator().manual_seed(42), use_cuda=False)

I0713 12:30:57.929148 4754986432 configuration_utils.py:264] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/dbmdz/bert-base-turkish-cased/config.json from cache at /Users/ilkerkurtulus/.cache/torch/transformers/85e4250979fc6fb434f8348f81373dd92b27cfe72fec7a7b0cee0649e168bcd8.a3aeed7cdac4ab32c23e706965d9605a64756bbc94becd5f14a720ed9debae9a
I0713 12:30:57.930298 4754986432 configuration_utils.py:300] Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 32000
}

I0713 12:30:58.052073 4754986432 modeling_utils.py:667] loading weights file https://cdn.huggingface.co/dbmdz/bert-base-t

In [79]:
import torch
gen0 = torch.Generator()
gen1 = torch.Generator()

gen0 = gen0.manual_seed(0)
gen1 = gen1.manual_seed(1)
torch.rand(5, generator=gen0)
torch.rand(5, generator=gen0)
torch.rand(5, generator=gen1)
torch.rand(5, generator=gen1)

gen0 = gen0.manual_seed(0)
gen1 = gen1.manual_seed(1)
torch.rand(5, generator=gen1)
torch.rand(5, generator=gen1)
torch.rand(5, generator=gen0)
torch.rand(5, generator=gen0)

tensor([0.6341, 0.4901, 0.8964, 0.4556, 0.6323])

In [80]:
gen0.manual_seed(0)

In [82]:
torch.rand(5, generator = torch.Generator().manual_seed(0))

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])

In [83]:
torch.rand(5, generator = torch.Generator().manual_seed(0))

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])

In [87]:
torch.rand(5, generator = torch.Generator().manual_seed(42))

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])

In [88]:
torch.rand(5, generator = torch.Generator().manual_seed(42))

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])